services:
  # Backend API Service
  - type: web
    name: safebrains-backend
    env: python
    plan: free
    rootDir: Backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Backend:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0

  # Frontend Static Site
  - type: web
    name: safebrains-frontend
    env: static
    plan: free
    rootDir: Frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://safebrains-backend.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 