services:
  - type: web
    name: safebrains-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Backend:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 